-- 在 Supabase 项目的 SQL Editor 里运行这段代码，创建记录表

create table lottery_log (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),  -- 抽签发生的时间
  activity text not null,                -- 抽到的项目
  status text not null default 'pending' -- pending=刚抽到还没反馈；done=完成了；skip=没做
    check (status in ('pending', 'done', 'skip'))
);

-- 开启行级安全策略（Supabase默认要求，否则前端读写会被拒绝）
alter table lottery_log enable row level security;

-- 允许任何人（也就是你的网页）插入和读取数据
-- 因为这是你自己的私人小工具，没有账号系统，所以用最简单的开放策略
create policy "允许插入" on lottery_log
  for insert to anon
  with check (true);

create policy "允许读取" on lottery_log
  for select to anon
  using (true);

-- 允许更新状态（抽签时先插入 pending，反馈时再更新为 done/skip）
create policy "允许更新" on lottery_log
  for update to anon
  using (true)
  with check (true);
