-- 在 Supabase 项目的 SQL Editor 里运行这段代码，创建记录表

create table lottery_log (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  activity text not null,
  status text not null check (status in ('done', 'skip'))
);

-- 开启行级安全策略（Supabase默认要求，否则前端读写会被拒绝）
alter table lottery_log enable row level security;

-- 允许任何人（也就是你的网页）插入和读取数据
-- 因为这是你自己的私人小工具，没有账号系统，所以用最简单的开放策略
create policy "允许插入" on lottery_log
  for insert to anon
  with check (true);

create policy "允许读取" on lottery_log
  for select to anon
  using (true);
