-- =============================================================
-- lab-play · events 表 schema（Supabase / Postgres）
-- -------------------------------------------------------------
-- events 是整个个人空间的共享时间线：玩法行动、面板里程碑统一写入；
-- 统计 / 图鉴 / 回顾是它的读视图。面板当前状态可由面板自己持有，
-- 不要求从 events 完整重建。
--
-- 设计原则（见 lab-play-system-design.md）：
--   · 单向流水账：只记录“发生了什么”，不做双向货币 / 消费出口。
--   · 记账动作要最轻：先把原始事件存下来，规则（分档、成就阈值）后置。
--   · 泛化字段：play / type / payload(JSON)，新增 play 不用改表结构。
--
-- 数据层：纯静态 + Supabase，前端直连本表（靠下面的 RLS 策略兜底）。
-- 在 Supabase 项目的 SQL Editor 里执行本脚本。
-- =============================================================

create table events (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),  -- 事件发生时间
  play        text not null,                        -- 哪个 play 产生的，如 'draw'
  type        text not null,                        -- 事件类型，如 'draw_pending' / 'draw_done' / 'draw_skip'
  payload     jsonb not null default '{}'::jsonb    -- 各 play 自定义内容
);

-- 常用查询：按 play + type 过滤（统计、图鉴规则扫描）
create index events_play_type_idx on events (play, type);

-- 常用查询：按时间范围（趋势、周期回顾）
create index events_created_at_idx on events (created_at);

-- =============================================================
-- 行级安全策略（RLS）
-- -------------------------------------------------------------
-- 所有人可读，只有 JWT app_metadata.role = owner 的账号可写。
-- owner claim 的配置步骤见 db/README.md；anon key 可公开，安全边界在 RLS。
-- =============================================================

alter table events enable row level security;

create policy "公开读取" on events
  for select to anon, authenticated
  using (true);

create policy "仅 owner 插入" on events
  for insert to authenticated
  with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'owner');

-- 抽卡两段式：先插入 draw_pending，反馈时再更新为 draw_done / draw_skip。
create policy "仅 owner 更新" on events
  for update to authenticated
  using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'owner')
  with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'owner');

-- =============================================================
-- 面板状态
-- -------------------------------------------------------------
-- panel_states 只放可公开展示的摘要；panel_private 放敏感正文。
-- 两者都是面板当前状态，不由 events 重建。
-- =============================================================

create table panel_states (
  panel       text primary key,
  state       jsonb not null default '{}'::jsonb,
  updated_at  timestamptz not null default now()
);

create table panel_private (
  panel       text primary key,
  content     jsonb not null default '{}'::jsonb,
  updated_at  timestamptz not null default now()
);

alter table panel_states enable row level security;
alter table panel_private enable row level security;

grant select on panel_states to anon, authenticated;
grant insert, update on panel_states to authenticated;
grant select, insert, update on panel_private to authenticated;

create policy "公开读取面板摘要" on panel_states
  for select to anon, authenticated
  using (true);

create policy "仅 owner 新增面板摘要" on panel_states
  for insert to authenticated
  with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'owner');

create policy "仅 owner 更新面板摘要" on panel_states
  for update to authenticated
  using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'owner')
  with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'owner');

create policy "仅 owner 读取私有面板" on panel_private
  for select to authenticated
  using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'owner');

create policy "仅 owner 新增私有面板" on panel_private
  for insert to authenticated
  with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'owner');

create policy "仅 owner 更新私有面板" on panel_private
  for update to authenticated
  using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'owner')
  with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'owner');

-- =============================================================
-- payload 约定（示例，非数据库强约束，由前端 core/events.js 保证）
-- -------------------------------------------------------------
-- 抽卡 play（play = 'draw'）：
--   type = 'draw_pending'  刚抽到、还没反馈
--   type = 'draw_done'     完成了
--   type = 'draw_skip'     没做
--   payload 例：{ "activity": "弹钢琴", "tier": "SR", "duration": 30 }
--
-- 两段式流程：抽中瞬间写一条 draw_pending，用户反馈后
-- 把这条记录的 type 更新为 draw_done / draw_skip。
--
-- Career panel（play = 'career'）：
--   type = 'career_milestone'
--   payload 例：{ "scope": "section", "section": "market_map",
--                 "from": "EMPTY", "to": "MAPPED" }
-- =============================================================
