-- =============================================================
-- lab-play · events 表 schema（Supabase / Postgres）
-- -------------------------------------------------------------
-- events 是整个个人空间的共享时间线：玩法行动、面板里程碑统一写入；
-- 统计 / 图鉴 / 回顾是它的读视图。面板当前状态可由面板自己持有，
-- 不要求从 events 完整重建。
--
-- 设计原则（见 lab-play-system-design.md）：
--   · 单向流水账：只记录“发生了什么”，不做双向货币 / 消费出口。
--   · 记账动作要最轻：先把原始事件存下来，规则（分档、成就阈值）后置。
--   · 泛化字段：play / type / payload(JSON)，新增 play 不用改表结构。
--
-- 数据层：纯静态 + Supabase，前端直连本表（靠下面的 RLS 策略兜底）。
-- 在 Supabase 项目的 SQL Editor 里执行本脚本。
-- =============================================================

create table events (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),  -- 事件发生时间
  play        text not null,                        -- 哪个 play 产生的，如 'draw'
  type        text not null,                        -- 事件类型，如 'draw_pending' / 'draw_done' / 'draw_skip'
  payload     jsonb not null default '{}'::jsonb    -- 各 play 自定义内容
);

-- 常用查询：按 play + type 过滤（统计、图鉴规则扫描）
create index events_play_type_idx on events (play, type);

-- 常用查询：按时间范围（趋势、周期回顾）
create index events_created_at_idx on events (created_at);

-- =============================================================
-- 行级安全策略（RLS）
-- -------------------------------------------------------------
-- 所有人可读，只有 JWT app_metadata.role = owner 的账号可写。
-- owner claim 的配置步骤见 db/README.md；anon key 可公开，安全边界在 RLS。
-- =============================================================

alter table events enable row level security;

create policy "公开读取" on events
  for select to anon, authenticated
  using (true);

create policy "仅 owner 插入" on events
  for insert to authenticated
  with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'owner');

-- 抽卡两段式：先插入 draw_pending，反馈时再更新为 draw_done / draw_skip。
create policy "仅 owner 更新" on events
  for update to authenticated
  using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'owner')
  with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'owner');

-- =============================================================
-- 面板状态
-- -------------------------------------------------------------
-- panel_states 只放可公开展示的摘要；panel_private 放敏感正文。
-- 两者都是面板当前状态，不由 events 重建。
-- =============================================================

create table panel_states (
  panel       text primary key,
  state       jsonb not null default '{}'::jsonb,
  updated_at  timestamptz not null default now()
);

create table panel_private (
  panel       text primary key,
  content     jsonb not null default '{}'::jsonb,
  updated_at  timestamptz not null default now()
);

alter table panel_states enable row level security;
alter table panel_private enable row level security;

grant select on panel_states to anon, authenticated;
grant insert, update on panel_states to authenticated;
grant select, insert, update on panel_private to authenticated;

create policy "公开读取面板摘要" on panel_states
  for select to anon, authenticated
  using (true);

create policy "仅 owner 新增面板摘要" on panel_states
  for insert to authenticated
  with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'owner');

create policy "仅 owner 更新面板摘要" on panel_states
  for update to authenticated
  using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'owner')
  with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'owner');

create policy "仅 owner 读取私有面板" on panel_private
  for select to authenticated
  using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'owner');

create policy "仅 owner 新增私有面板" on panel_private
  for insert to authenticated
  with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'owner');

create policy "仅 owner 更新私有面板" on panel_private
  for update to authenticated
  using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'owner')
  with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'owner');

-- =============================================================
-- payload 约定（示例，非数据库强约束，由前端 core/events.js 保证）
-- -------------------------------------------------------------
-- 抽卡 play（play = 'draw'）：
--   type = 'draw_pending'  刚抽到、还没反馈
--   type = 'draw_done'     完成了
--   type = 'draw_skip'     没做
--   payload 例：{ "activity": "弹钢琴", "tier": "SR", "duration": 30 }
--
-- 两段式流程：抽中瞬间写一条 draw_pending，用户反馈后
-- 把这条记录的 type 更新为 draw_done / draw_skip。
--
-- Career panel（play = 'career'）：
--   type = 'career_milestone'
--   payload 例：{ "scope": "section", "section": "market_map",
--                 "from": "EMPTY", "to": "MAPPED" }
-- =============================================================

-- =============================================================
-- 原子写入与备份恢复 RPC
-- =============================================================

create or replace function public.save_career_panel(
  p_state jsonb,
  p_private jsonb,
  p_milestones jsonb default '[]'::jsonb
) returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_milestones integer := 0;
begin
  if coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') <> 'owner' then
    raise exception 'owner required' using errcode = '42501';
  end if;
  insert into public.panel_private(panel, content, updated_at)
  values ('career', p_private, now())
  on conflict (panel) do update set content = excluded.content, updated_at = excluded.updated_at;
  insert into public.panel_states(panel, state, updated_at)
  values ('career', p_state, now())
  on conflict (panel) do update set state = excluded.state, updated_at = excluded.updated_at;
  insert into public.events(play, type, payload)
  select 'career', 'career_milestone', value
  from jsonb_array_elements(coalesce(p_milestones, '[]'::jsonb));
  get diagnostics v_milestones = row_count;
  return jsonb_build_object('state', p_state, 'content', p_private, 'milestones', v_milestones);
end;
$$;

revoke all on function public.save_career_panel(jsonb, jsonb, jsonb) from public, anon;
grant execute on function public.save_career_panel(jsonb, jsonb, jsonb) to authenticated;

create or replace function public.restore_lab_play_backup(p_backup jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_events integer := 0;
  v_states integer := 0;
  v_private integer := 0;
  v_max_id bigint;
begin
  if coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') <> 'owner' then
    raise exception 'owner required' using errcode = '42501';
  end if;
  if p_backup ->> 'format' <> 'lab-play-backup'
     or coalesce((p_backup ->> 'version')::integer, 0) <> 1 then
    raise exception 'unsupported backup format' using errcode = '22023';
  end if;
  insert into public.events(id, created_at, play, type, payload)
  select id, created_at, play, type, payload
  from jsonb_to_recordset(coalesce(p_backup -> 'events', '[]'::jsonb))
    as item(id bigint, created_at timestamptz, play text, type text, payload jsonb)
  on conflict (id) do update set created_at = excluded.created_at, play = excluded.play, type = excluded.type, payload = excluded.payload;
  get diagnostics v_events = row_count;
  insert into public.panel_states(panel, state, updated_at)
  select panel, state, updated_at
  from jsonb_to_recordset(coalesce(p_backup -> 'panel_states', '[]'::jsonb))
    as item(panel text, state jsonb, updated_at timestamptz)
  on conflict (panel) do update set state = excluded.state, updated_at = excluded.updated_at;
  get diagnostics v_states = row_count;
  insert into public.panel_private(panel, content, updated_at)
  select panel, content, updated_at
  from jsonb_to_recordset(coalesce(p_backup -> 'panel_private', '[]'::jsonb))
    as item(panel text, content jsonb, updated_at timestamptz)
  on conflict (panel) do update set content = excluded.content, updated_at = excluded.updated_at;
  get diagnostics v_private = row_count;
  select max(id) into v_max_id from public.events;
  if v_max_id is null then
    perform setval(pg_get_serial_sequence('public.events', 'id'), 1, false);
  else
    perform setval(pg_get_serial_sequence('public.events', 'id'), v_max_id, true);
  end if;
  return jsonb_build_object('events', v_events, 'panel_states', v_states, 'panel_private', v_private);
end;
$$;

revoke all on function public.restore_lab_play_backup(jsonb) from public, anon;
grant execute on function public.restore_lab_play_backup(jsonb) to authenticated;
