-- =============================================================
-- lab-play · events 表 schema（Supabase / Postgres）
-- -------------------------------------------------------------
-- 这是整个游戏系统的“唯一真相源”（single source of truth）。
-- 所有 play 产生的行为都统一写成一条 event；统计 / 图鉴 / 回顾
-- 都只是对这张表的读视图，不单独存状态、不新增业务表。
--
-- 设计原则（见 lab-play-system-design.md）：
--   · 单向流水账：只记录“发生了什么”，不做双向货币 / 消费出口。
--   · 记账动作要最轻：先把原始事件存下来，规则（分档、成就阈值）后置。
--   · 泛化字段：play / type / payload(JSON)，新增 play 不用改表结构。
--
-- 数据层：纯静态 + Supabase，前端直连本表（靠下面的 RLS 策略兜底）。
-- 在 Supabase 项目的 SQL Editor 里执行本脚本。
-- =============================================================

create table events (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),  -- 事件发生时间
  play        text not null,                        -- 哪个 play 产生的，如 'draw'
  type        text not null,                        -- 事件类型，如 'draw_pending' / 'draw_done' / 'draw_skip'
  payload     jsonb not null default '{}'::jsonb    -- 各 play 自定义内容
);

-- 常用查询：按 play + type 过滤（统计、图鉴规则扫描）
create index events_play_type_idx on events (play, type);

-- 常用查询：按时间范围（趋势、周期回顾）
create index events_created_at_idx on events (created_at);

-- =============================================================
-- 行级安全策略（RLS）
-- -------------------------------------------------------------
-- Supabase 默认要求开 RLS，否则前端读写会被拒。因为这是私人小工具、
-- 没有账号系统，用最简单的开放策略：允许匿名（anon）读 / 写 / 改。
-- anon key 是设计成可公开的，安全边界靠这里的策略控制。
-- =============================================================

alter table events enable row level security;

create policy "允许插入" on events
  for insert to anon
  with check (true);

create policy "允许读取" on events
  for select to anon
  using (true);

-- 抽卡两段式：先插入 draw_pending，反馈时再更新为 draw_done / draw_skip
create policy "允许更新" on events
  for update to anon
  using (true)
  with check (true);

-- =============================================================
-- payload 约定（示例，非数据库强约束，由前端 core/events.js 保证）
-- -------------------------------------------------------------
-- 抽卡 play（play = 'draw'）：
--   type = 'draw_pending'  刚抽到、还没反馈
--   type = 'draw_done'     完成了
--   type = 'draw_skip'     没做
--   payload 例：{ "activity": "弹钢琴", "tier": "SR", "duration": 30 }
--
-- 两段式流程：抽中瞬间写一条 draw_pending，用户反馈后
-- 把这条记录的 type 更新为 draw_done / draw_skip。
-- =============================================================
